"use client";
import { useRouter } from "next/navigation";
export default function TermsPage() {
  const router = useRouter();
  const handleAgree = () => {
    router.push("/onboarding/register?agreed=true");
  };
  return (
    <div className="min-h-screen bg-white flex items-center justify-center p-4">
      <div className="w-full max-w-3xl bg-gray-50 text-gray-800 rounded-xl overflow-hidden shadow-lg border border-gray-200">
        <div className="p-5 border-b border-gray-200 flex justify-between items-center sticky top-0 bg-gray-50 z-10">
          <h1 className="text-2xl md:text-3xl font-semibold text-gray-800">Terms and Conditions</h1>
          <button
            onClick={() => router.back()}
            className="text-gray-500 hover:text-gray-800 text-4xl cursor-pointer w-8 h-8 flex items-center justify-center"
            aria-label="Close"
          >
            &times;
          </button>
        </div>
        <div className="max-h-[70vh] overflow-y-auto p-6 text-base leading-relaxed text-gray-700">

          <div className="mb-6 p-4 bg-yellow-50 border border-yellow-200 rounded-lg">
            <p className="text-sm text-yellow-800 font-medium">
              ⚠ Demo Notice: This is a demonstration instance. It is intended for evaluation and research purposes only. Data entered on this platform may be deleted at any time without prior notice. 
            </p>
          </div>

          <section className="mb-6">
            <h2 className="text-lg font-semibold text-gray-800 mb-2">1. Introduction</h2>
            <p>
              Welcome to Tesfa. By accessing this platform, you agree to these Terms and Conditions. Please read them before proceeding.
            </p>
          </section>
          <section className="mb-6">
            <h2 className="text-lg font-semibold text-gray-800 mb-2">2. About This Platform</h2>
            <p>
              Tesfa is an AI-powered proof-of-concept platform developed to support NGOs, health agencies, and policymakers working in conflict-affected regions. It provides AI-generated health risk predictions and insights to assist in planning and decision-making. This instance is a demo and is not intended for production use.
            </p>
          </section>
          <section className="mb-6">
            <h2 className="text-lg font-semibold text-gray-800 mb-2">3. Your Responsibilities</h2>
            <p>When using Tesfa, you agree to:</p>
            <ul className="list-disc pl-5 space-y-1 mt-2">
              <li>Provide accurate information when creating or managing your account.</li>
              <li>Use the platform only for legitimate research, evaluation, or organizational purposes.</li>
              <li>Keep your login credentials confidential.</li>
            </ul>
          </section>
          <section className="mb-6">
            <h2 className="text-lg font-semibold text-gray-800 mb-2">4. Data and Privacy</h2>
            <p>
              We collect limited information such as your name, email, and organization to provide a personalized experience. Tesfa follows applicable data protection regulations including the Kenya Data Protection Act (2019) and GDPR where relevant. By using this platform, you consent to the collection and use of your data as described here. As this is a demo instance, please avoid entering sensitive or confidential information.
            </p>
          </section>
          <section className="mb-6">
            <h2 className="text-lg font-semibold text-gray-800 mb-2">5. AI-Generated Content</h2>
            <p>
              All predictions, reports, and recommendations on this platform are generated by artificial intelligence based on available conflict health data. While we aim for accuracy, AI-generated content may contain errors or limitations. Outputs should be treated as indicative and should not replace expert medical, humanitarian, or policy judgment.
            </p>
          </section>
          <section className="mb-6">
            <h2 className="text-lg font-semibold text-gray-800 mb-2">6. Acceptable Use</h2>
            <p>You agree not to:</p>
            <ul className="list-disc pl-5 space-y-1 mt-2">
              <li>Use Tesfa for illegal, unethical, or harmful activities.</li>
              <li>Upload or share false, misleading, or confidential data without permission.</li>
              <li>Attempt to interfere with or disrupt the platform's systems or security.</li>
            </ul>
          </section>
          <section className="mb-6">
            <h2 className="text-lg font-semibold text-gray-800 mb-2">7. Limitation of Liability</h2>
            <p>
              Tesfa is a decision-support tool provided as-is for demonstration purposes. We are not liable for any losses, damages, or decisions made based on the platform's outputs. We make no guarantees that data will always be complete, accurate, or available.
            </p>
          </section>
          <section className="mb-6">
            <h2 className="text-lg font-semibold text-gray-800 mb-2">8. Contact Us</h2>
            <p>
              For questions, feedback, or data-related requests, please contact us at:
              <br />
              <a href="mailto:info@onainsights.io" className="font-medium text-primary">info@onainsights.io</a>
              <br />
              Nairobi, Kenya
            </p>
          </section>
        </div>
        <div className="p-4 border-t border-gray-200 bg-gray-50 flex justify-end">
          <button
            onClick={handleAgree}
            className="px-5 py-2 cursor-pointer bg-primary text-white font-semibold rounded-lg hover:bg-primary-dark transition"
          >
            Agree
          </button>
        </div>
      </div>
    </div>
  );
}